# Generated by Django 6.1 on 2026-08-20 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='القسم')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='المسمى الوظيفي')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الجنسية')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المنشأة')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم الموظف')),
                ('employee_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الموظف')),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الهوية / الإقامة')),
                ('employee_type', models.CharField(choices=[('رسمي', 'رسمي'), ('متعاقد', 'متعاقد'), ('تشغيل ذاتي', 'تشغيل ذاتي'), ('أخرى', 'أخرى')], max_length=50, verbose_name='نوع الموظف')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('dob', models.DateField(verbose_name='تاريخ الميلاد')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('general_specialty', models.CharField(max_length=100, verbose_name='التخصص العام')),
                ('sub_specialty', models.CharField(max_length=100, verbose_name='التخصص الدقيق')),
                ('is_classified', models.BooleanField(default=False, verbose_name='مصنف (نعم/لا)')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العقد')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العقد')),
                ('is_admin_assigned', models.BooleanField(default=False, verbose_name='مكلف بعمل إداري')),
                ('admin_work_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='تفاصيل العمل الإداري')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees.department', verbose_name='القسم')),
                ('contract_job_title', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees.jobtitle', verbose_name='المسمى الوظيفي للعقد')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees.nationality', verbose_name='الجنسية')),
                ('current_workplace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employees.workplace', verbose_name='اسم المنشأة')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('سنوية', 'سنوية'), ('مرضية', 'مرضية'), ('اضطرارية', 'اضطرارية'), ('استثنائية', 'استثنائية')], max_length=50, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الإجازة')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الإجازة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee', verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.workplace', verbose_name='المنشأة التابع لها')),
            ],
        ),
    ]
