# Generated by Django 6.1 on 2026-08-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_classified',
            field=models.CharField(choices=[('مصنف', 'مصنف'), ('غير مصنف', 'غير مصنف')], default='غير مصنف', max_length=20, verbose_name='حالة التصنيف'),
        ),
    ]
