# Generated by Django 6.1 on 2026-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_is_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('نشط', 'نشط'), ('مستقيل', 'مستقيل'), ('موقوف', 'موقوف'), ('مقال', 'مقال')], default='نشط', max_length=20, verbose_name='حالة الموظف'),
        ),
    ]
