# Generated by Django 6.1 on 2026-08-22 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('إضافة', 'إضافة'), ('تعديل', 'تعديل'), ('حذف', 'حذف'), ('استعادة', 'استعادة'), ('نظام', 'نظام')], max_length=20, verbose_name='نوع الإجراء')),
                ('description', models.CharField(max_length=255, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت والتاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
