# Generated by Django 6.1 on 2026-08-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التخصص العام')),
            ],
        ),
        migrations.CreateModel(
            name='SubSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التخصص الدقيق')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='general_specialty',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sub_specialty',
        ),
    ]
