# Generated by Django 6.1 on 2026-08-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_generalspecialty_subspecialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='general_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.generalspecialty', verbose_name='التخصص العام'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.subspecialty', verbose_name='التخصص الدقيق'),
        ),
    ]
