# Generated by Django 6.1 on 2026-08-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_general_specialty_employee_sub_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='classification_expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ انتهاء التصنيف'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ انتهاء العقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('نشط', 'نشط'), ('مستقيل', 'مستقيل'), ('موقوف', 'موقوف'), ('مقال', 'مقال')], db_index=True, default='نشط', max_length=20, verbose_name='حالة الموظف'),
        ),
        migrations.AlterField(
            model_name='generalspecialty',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='التخصص العام'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ نهاية الإجازة'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ بداية الإجازة'),
        ),
        migrations.AlterField(
            model_name='subspecialty',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='التخصص الدقيق'),
        ),
    ]
