# Generated by Django 6.1 on 2026-08-26 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_classification_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('سعودي', 'سعودي'), ('مصري', 'مصري'), ('أردني', 'أردني'), ('سوداني', 'سوداني'), ('سوري', 'سوري'), ('فلسطيني', 'فلسطيني'), ('يمني', 'يمني'), ('لبناني', 'لبناني'), ('عراقي', 'عراقي'), ('تونسي', 'تونسي'), ('مغربي', 'مغربي'), ('جزائري', 'جزائري'), ('ليبي', 'ليبي'), ('عماني', 'عماني'), ('إماراتي', 'إماراتي'), ('كويتي', 'كويتي'), ('بحريني', 'بحريني'), ('قطري', 'قطري'), ('هندي', 'هندي'), ('فلبيني', 'فلبيني'), ('باكستاني', 'باكستاني'), ('بنغلاديشي', 'بنغلاديشي'), ('إندونيسي', 'إندونيسي'), ('سريلانكي', 'سريلانكي'), ('نيبالي', 'نيبالي'), ('ماليزي', 'ماليزي'), ('أمريكي', 'أمريكي'), ('بريطاني', 'بريطاني'), ('كندي', 'كندي'), ('أسترالي', 'أسترالي'), ('جنوب أفريقي', 'جنوب أفريقي'), ('نيجيري', 'نيجيري'), ('كينى', 'كينى'), ('تركي', 'تركي'), ('أخرى', 'أخرى')], default='سعودي', max_length=50, verbose_name='الجنسية'),
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(max_length=50, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='الوقت والتاريخ'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الإدارة / القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='admin_work_details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل العمل الإداري'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.jobtitle', verbose_name='المسمى الوظيفي بالعقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='الإدارة / القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.workplace', verbose_name='المنشأة الحالية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='فئة الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='الاسم الرباعي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_admin_assigned',
            field=models.BooleanField(default=False, verbose_name='يوجد تكليف إداري؟'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهوية / الإقامة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('نشط', 'نشط'), ('مستقيل', 'مستقيل'), ('موقوف', 'موقوف'), ('مقال', 'مقال')], default='نشط', max_length=20, verbose_name='حالة الموظف'),
        ),
        migrations.AlterField(
            model_name='generalspecialty',
            name='name',
            field=models.CharField(max_length=150, verbose_name='التخصص العام'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=150, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('سنوية', 'سنوية'), ('مرضية', 'مرضية'), ('اضطرارية', 'اضطرارية'), ('أخرى', 'أخرى')], max_length=50, verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='subspecialty',
            name='name',
            field=models.CharField(max_length=150, verbose_name='التخصص الدقيق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المنشأة'),
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
