# Generated by Django 6.1 on 2026-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_nationality_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('تشغيل ذاتي', 'تشغيل ذاتي'), ('خدمة مدنية', 'خدمة مدنية')], max_length=50, null=True, verbose_name='فئة الموظف'),
        ),
    ]
