# Generated by Django 6.1 on 2026-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_job_title',
            field=models.CharField(blank=True, choices=[('مقيم', 'طبيب مقيم'), ('نائب', 'طبيب نائب'), ('نائب أول', 'طبيب نائب أول'), ('استشاري', 'طبيب استشاري'), ('طبيب عام', 'طبيب عام'), ('أخصائي', 'أخصائي'), ('فني', 'فني'), ('تمريض', 'تمريض'), ('إداري', 'إداري'), ('مدير', 'مدير'), ('أخرى', 'أخرى')], max_length=50, null=True, verbose_name='المسمى الوظيفي بالعقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('نشط', 'نشط'), ('مستقيل', 'مستقيل'), ('طي القيد', 'طي القيد'), ('إيفاد', 'إيفاد')], default='نشط', max_length=20, verbose_name='حالة الموظف'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
