# Generated by Django 6.1 on 2026-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_current_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_job_title',
            field=models.CharField(blank=True, choices=[('مقيم', 'طبيب مقيم'), ('نائب', 'طبيب نائب'), ('نائب أول', 'نائب أول'), ('استشاري', 'طبيب استشاري')], max_length=50, null=True, verbose_name='المسمى الوظيفي بالعقد'),
        ),
    ]
