# Generated by Django 6.1 on 2026-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_contract_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='القسم الذي يعمل به'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(blank=True, choices=[('مقيم', 'طبيب مقيم'), ('نائب', 'طبيب نائب'), ('نائب أول', 'نائب أول'), ('استشاري', 'طبيب استشاري')], max_length=50, null=True, verbose_name='فئة الموظف (الكادر)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_sub_specialty',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=10, verbose_name='هل يوجد تخصص دقيق؟'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_type',
            field=models.CharField(blank=True, choices=[('جزئي', 'جزئي'), ('كلي', 'كلي')], max_length=20, null=True, verbose_name='التفرغ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workplace_type',
            field=models.CharField(blank=True, choices=[('مستشفى عام', 'مستشفى عام'), ('مدن طبية', 'مدن طبية'), ('جامعة الملك خالد', 'جامعة الملك خالد')], max_length=50, null=True, verbose_name='نوع المنشأة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المسمى الوظيفي بالعقد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('تشغيل ذاتي', 'تشغيل ذاتي'), ('خدمة مدنية', 'خدمة مدنية'), ('عقود الصحة القابضة', 'عقود الصحة القابضة')], max_length=50, null=True, verbose_name='فئة الموظف'),
        ),
    ]
