# Generated by Django 5.2.17 on 2026-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_alter_employee_employee_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="workplace_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نوع المنشأة"
            ),
        ),
    ]
