# Generated by Django 5.2.17 on 2026-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0016_alter_employee_workplace_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="archive_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="سبب النقل للأرشيف"
            ),
        ),
    ]
