# Generated by Django 5.2.17 on 2026-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0017_employee_archive_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="classification_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رقم تصنيف الموظف"
            ),
        ),
    ]
