# Generated by Django 6.1 on 2026-09-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_archive_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('تشغيل ذاتي', 'تشغيل ذاتي'), ('خدمة مدنية', 'خدمة مدنية')], max_length=50, null=True, verbose_name='نوع الموظف'),
        ),
    ]
