# Generated by Django 5.2.17 on 2026-09-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0018_alter_employee_employee_type"),
        ("employees", "0018_employee_classification_number"),
    ]

    operations = []
