# Generated by Django 5.2.17 on 2026-09-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0021_swap_nationality_to_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="current_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.department",
                verbose_name="القسم الذي يعمل به",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_workplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.workplace",
                verbose_name="المنشأة الحالية",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="general_specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.generalspecialty",
                verbose_name="التخصص العام",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="sub_specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.subspecialty",
                verbose_name="التخصص الدقيق",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="workplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.workplace",
                verbose_name="المنشأة التابع لها",
            ),
        ),
    ]
